name: intern_ai_app
description: "Intern-AI - Your Personal Career Assistant"
publish_to: 'none'
version: 1.3.0+6

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_database: ^11.3.5
  google_sign_in: ^6.2.2
  
  # Networking
  http: ^1.3.0
  
  # UI & Markdown
  flutter_markdown: ^0.7.4
  
  # State Management
  provider: ^6.1.4
  
  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  
  # UI
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
